var searchData=
[
  ['syntax',['Syntax',['../api_files_syntax.html',1,'apiFiles']]],
  ['security',['Security',['../basic_security.html',1,'basicConcepts']]],
  ['sandboxes',['Sandboxes',['../basic_security_sandbox.html',1,'basicSecurity']]],
  ['smack',['SMACK',['../basic_security_smack.html',1,'basicSecurity']]],
  ['sample_20code_20of_20audio_20playback_20and_20capture',['Sample code of audio playback and capture',['../c_audio_capture_playback.html',1,'']]],
  ['sample_20code_20of_20dtmf_20playback_20and_20decoding',['Sample code of dtmf playback and decoding',['../c_audiodtmf.html',1,'']]],
  ['sample_20code_20of_20audio_20settings_20for_20a_20dialing_20call',['Sample code of audio settings for a dialing call',['../c_audio_mcc.html',1,'']]],
  ['system_20clock_20api',['System Clock API',['../c_clock.html',1,'c_APIs']]],
  ['sample_20code_20of_20an_20ecall_20test_20session_20with_20a_20local_20voice_20prompt',['Sample code of an eCall test session with a local voice prompt',['../c_ecall_w_prompt_sample.html',1,'']]],
  ['sample_20code_20an_20ecall_20test_20session_20with_20a_20voice_20call_20connection',['Sample code an eCall test session with a voice call connection',['../c_ecall_w_voice_sample.html',1,'']]],
  ['sample_20code_20of_20modem_20call_20control',['Sample code of Modem Call control',['../c_mcc_test.html',1,'']]],
  ['sample_20code_20for_20data_20profiles',['Sample code for Data Profiles',['../c_mdc_data_profiles.html',1,'c_mdc']]],
  ['sample_20code_20for_20network_20interface_20settings',['Sample code for network interface settings',['../c_mdc_data_sessions.html',1,'c_mdc']]],
  ['sample_20code_20for_20data_20statistics',['Sample code for Data Statistics',['../c_mdc_data_statistics.html',1,'c_mdc']]],
  ['sample_20code_20for_20band_20capabilities',['Sample code for Band Capabilities',['../c_mrc_band_capabilities.html',1,'c_mrc']]],
  ['sample_20code_20for_20get_20current_20network_20information',['Sample code for Get Current Network Information',['../c_mrc_get_current_network.html',1,'c_mrc']]],
  ['sample_20code_20for_20location_20information',['Sample code for Location information',['../c_mrc_locationinformation.html',1,'c_mrc']]],
  ['sample_20code_20for_20neighboring_20cells_20information',['Sample code for Neighboring Cells Information',['../c_mrc_neighbor_cells.html',1,'c_mrc']]],
  ['sample_20code_20for_20network_20registration',['Sample code for Network Registration',['../c_mrc_network_registration.html',1,'c_mrc']]],
  ['sample_20code_20for_20network_20scan',['Sample code for Network Scan',['../c_mrc_network_scan.html',1,'c_mrc']]],
  ['sample_20code_20for_20signal_20quality',['Sample code for Signal Quality',['../c_mrc_quality.html',1,'c_mrc']]],
  ['sample_20code_20for_20radio_20configuration_20preferences',['Sample code for Radio Configuration Preferences',['../c_mrc_radio_configuration_preferences.html',1,'c_mrc']]],
  ['sample_20code_20for_20radio_20power_20management',['Sample code for Radio Power Management',['../c_mrc_radio_power.html',1,'c_mrc']]],
  ['sample_20code_20for_20radio_20access_20technology',['Sample code for Radio Access Technology',['../c_mrc_r_a_t.html',1,'c_mrc']]],
  ['safe_20references_20api',['Safe References API',['../c_safe_ref.html',1,'c_APIs']]],
  ['secure_20storage',['Secure Storage',['../c_sec_store.html',1,'legatoServicesSecStoreMain']]],
  ['secure_20storage_20admin',['Secure Storage Admin',['../c_sec_store_admin.html',1,'legatoServicesSecStoreMain']]],
  ['semaphore_20api',['Semaphore API',['../c_semaphore.html',1,'c_APIs']]],
  ['signals_20api',['Signals API',['../c_signals.html',1,'c_APIs']]],
  ['sim',['SIM',['../c_sim.html',1,'legatoServicesModem']]],
  ['sample_20code_20for_20sim_20authentication',['Sample code for SIM Authentication',['../c_sim_test_authentication.html',1,'c_sim']]],
  ['sample_20code_20for_20sim_20identification',['Sample code for SIM Identification',['../c_sim_test_identification.html',1,'c_sim']]],
  ['sample_20code_20for_20local_20sim_20profile_20switch',['Sample code for Local SIM profile switch',['../c_sim_test_profile_switch.html',1,'c_sim']]],
  ['sample_20code_20for_20sim_20select',['Sample code for SIM Select',['../c_sim_test_select.html',1,'c_sim']]],
  ['sample_20code_20for_20local_20sim_20toolkit',['Sample code for Local SIM Toolkit',['../c_sim_test_sim_toolkit.html',1,'c_sim']]],
  ['sample_20code_20for_20sim_20states',['Sample code for SIM States',['../c_sim_test_states.html',1,'c_sim']]],
  ['singly_20linked_20list_20api',['Singly Linked List API',['../c_singly_linked_list.html',1,'c_APIs']]],
  ['sms',['SMS',['../c_sms.html',1,'legatoServicesSMS']]],
  ['sample_20code_20for_20sms_20cell_20broadcast_20reception',['Sample code for SMS Cell Broadcast reception',['../c_sms_cb_sample.html',1,'']]],
  ['sms_20inbox_20service',['SMS Inbox Service',['../c_sms_inbox.html',1,'legatoServicesSMS']]],
  ['sample_20code_20for_20mobile_20originated_20sms_20message',['Sample code for Mobile Originated SMS message',['../c_sms_sample_m_o.html',1,'c_sms']]],
  ['sample_20code_20for_20mobile_20terminated_20sms_20message',['Sample code for Mobile Terminated SMS message',['../c_sms_sample_m_t.html',1,'c_sms']]],
  ['supervisor_20control_20api',['Supervisor Control API',['../c_sup_ctrl.html',1,'legatoServicesSupervisorMonitoring']]],
  ['supervisor_20watchdog_20api',['Supervisor Watchdog API',['../c_sup_wdog.html',1,'']]],
  ['software_20update',['Software Update',['../c_update.html',1,'legatoServicesUpdateMain']]],
  ['system_20definition_20_2esdef',['System Definition .sdef',['../def_files_sdef.html',1,'defFiles']]],
  ['software_20package_20manager',['Software Package Manager',['../getstarted_d_sspm.html',1,'']]],
  ['setup_20dev_20host_20pc',['Setup Dev Host PC',['../getstarted_setup_host.html',1,'getstartedMain']]],
  ['setup_20target_20device',['Setup Target Device',['../getstarted_target_main.html',1,'getstartedMain']]],
  ['setup_20target_20software',['Setup Target Software',['../getstarted_target_s_w.html',1,'getstartedCLinstallMain']]],
  ['set_20user_20timebase',['Set User Timebase',['../how_to_set_user_timebase.html',1,'howToMain']]],
  ['services_20apis',['Services APIs',['../legato_services.html',1,'apiGuidesMain']]],
  ['secure_20storage',['Secure Storage',['../legato_services_sec_store_main.html',1,'legatoServices']]],
  ['sms_20messaging',['SMS Messaging',['../legato_services_s_m_s.html',1,'legatoServices']]],
  ['supervisor',['Supervisor',['../legato_services_supervisor.html',1,'legatoServices']]],
  ['supervisor_20monitoring',['Supervisor Monitoring',['../legato_services_supervisor_monitoring.html',1,'legatoServicesSupervisor']]],
  ['secure_20storage',['Secure Storage',['../platform_constraints_sec_storage.html',1,'platformConstraints']]],
  ['sample_20apps',['Sample Apps',['../sample_apps.html',1,'getstartedMain']]],
  ['shell_20piping',['Shell Piping',['../sample_apps_shell_piping.html',1,'sampleApps']]],
  ['sms',['SMS',['../sample_apps_sms.html',1,'sampleApps']]],
  ['sec',['sec',['../structle__clk___time__t.html#ae28e527dbd551b3537edc1737611782f',1,'le_clk_Time_t']]],
  ['secstoreadmin_5fconnectservice',['secStoreAdmin_ConnectService',['../sec_store_admin__interface_8h.html#ad9231c3f63c28740ce137937575512f7',1,'secStoreAdmin_interface.h']]],
  ['secstoreadmin_5fcreateiter',['secStoreAdmin_CreateIter',['../sec_store_admin__interface_8h.html#af9ad6040381e49255b70c344984f065f',1,'secStoreAdmin_interface.h']]],
  ['secstoreadmin_5fdelete',['secStoreAdmin_Delete',['../sec_store_admin__interface_8h.html#a7099f4b5e2a7b03dee054e73f9ec1c1b',1,'secStoreAdmin_interface.h']]],
  ['secstoreadmin_5fdeleteiter',['secStoreAdmin_DeleteIter',['../sec_store_admin__interface_8h.html#a1b2bfa514f93235bf5fffd3e098abf4a',1,'secStoreAdmin_interface.h']]],
  ['secstoreadmin_5fdisconnectservice',['secStoreAdmin_DisconnectService',['../sec_store_admin__interface_8h.html#ab3077b62ed029fa6d6d286c1b2e1c9bd',1,'secStoreAdmin_interface.h']]],
  ['secstoreadmin_5fgetentry',['secStoreAdmin_GetEntry',['../sec_store_admin__interface_8h.html#a69e0766bf0200b449f443a348c04bdac',1,'secStoreAdmin_interface.h']]],
  ['secstoreadmin_5fgetsize',['secStoreAdmin_GetSize',['../sec_store_admin__interface_8h.html#a4a7a4ddc84fe087a1dc6e22ec9d6fa28',1,'secStoreAdmin_interface.h']]],
  ['secstoreadmin_5fgettotalspace',['secStoreAdmin_GetTotalSpace',['../sec_store_admin__interface_8h.html#ac8eb38a1cdd75ff734a222bb129456f9',1,'secStoreAdmin_interface.h']]],
  ['secstoreadmin_5finterface_2eh',['secStoreAdmin_interface.h',['../sec_store_admin__interface_8h.html',1,'']]],
  ['secstoreadmin_5fiterref_5ft',['secStoreAdmin_IterRef_t',['../sec_store_admin__interface_8h.html#abdd281dcdd0bd6a42ccf4ab6581ad6e9',1,'secStoreAdmin_interface.h']]],
  ['secstoreadmin_5fmax_5fpath_5fsize',['SECSTOREADMIN_MAX_PATH_SIZE',['../sec_store_admin__interface_8h.html#a659f4fc5eeb34940d06443436bf55d50',1,'secStoreAdmin_interface.h']]],
  ['secstoreadmin_5fnext',['secStoreAdmin_Next',['../sec_store_admin__interface_8h.html#afb7ecb1215f1fde24ed693ef10069052',1,'secStoreAdmin_interface.h']]],
  ['secstoreadmin_5fread',['secStoreAdmin_Read',['../sec_store_admin__interface_8h.html#a99df42615c4ab6c8ec1eb0f2f69176ea',1,'secStoreAdmin_interface.h']]],
  ['secstoreadmin_5fwrite',['secStoreAdmin_Write',['../sec_store_admin__interface_8h.html#a6799053e02e9e9e9a84d286d1bebfedc',1,'secStoreAdmin_interface.h']]],
  ['stringize',['STRINGIZE',['../le__basics_8h.html#a3428692efe6051ef30016ffde1a9f7bb',1,'le_basics.h']]],
  ['stringize_5fexpand',['STRINGIZE_EXPAND',['../le__basics_8h.html#a323e322ff5c06971560903199f1a4f68',1,'le_basics.h']]],
  ['security_2dpack',['security-pack',['../tools_host_security-pack.html',1,'toolsHost']]],
  ['setname',['setname',['../tools_host_setname.html',1,'toolsHost']]],
  ['settime',['settime',['../tools_host_settime.html',1,'toolsHost']]],
  ['settz',['settz',['../tools_host_settz.html',1,'toolsHost']]],
  ['simu',['simu',['../tools_host_simu.html',1,'toolsHost']]],
  ['startapp',['startapp',['../tools_host_startapp.html',1,'toolsHost']]],
  ['startlegato',['startlegato',['../tools_host_startlegato.html',1,'toolsHost']]],
  ['statapp',['statapp',['../tools_host_statapp.html',1,'toolsHost']]],
  ['stopapp',['stopapp',['../tools_host_stopapp.html',1,'toolsHost']]],
  ['stoplegato',['stoplegato',['../tools_host_stoplegato.html',1,'toolsHost']]],
  ['sdir',['sdir',['../tools_target_sdir.html',1,'toolsTarget']]],
  ['setnet',['setNet',['../tools_target_set_net.html',1,'toolsTarget']]]
];
